name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]



jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        sub_module: [container, logs, cast, kflow]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build
      working-directory: ${{github.workspace}}/${{matrix.sub_module}}
      run: go build -v .

    - name: Test
      working-directory: ${{github.workspace}}/${{matrix.sub_module}}
      run: go test -v ./... -race -coverprofile=coverage.out -covermode=atomic

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
